config/routes.rb
CmsSetup::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'integrations#index'

  resources :integrations, only: [:index, :show]

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  has_many :integrations
  has_many :integration_edits
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/integration.rb
class Integration < ActiveRecord::Base
  belongs_to :admin_user
  has_many :integration_edits

  validates :title,
    presence: true

  scope :visible, lambda { where(visible: true) }

  def newest_integration_edit
    integration_edits.order(:created_at).last
  end
end

app/models/integration_edit.rb
class IntegrationEdit < ActiveRecord::Base
  belongs_to :integration
  belongs_to :admin_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController

  layout 'public'

  def index
    if current_admin_user
      @integrations = Integration.all
    else
      @integrations = Integration.visible.all
    end
  end

  def show
    @integration = Integration.find(params[:id])
    if @integration.visible
      #show the page
    else
      if current_admin_user
        #show page
      else
        redirect_to integrations_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/views/integrations/index.html.haml
%h1 Integration's index

%table
  %tr
    %th
      Integration
    %th
      Connection Type
    %th
  - @integrations.each do |integration|
    %tr
      %td
        = integration.title
      %td
        = integration.connection_type
      %td
        = link_to integration.title, integration_path(integration.id)

app/views/integrations/show.html.haml
= content_for :header do
  = link_to 'Edit Integration', edit_admin_integration_path

%h1 Integration Show

%h2
  = @integration.title

%section
  = @integration.custom_instructions

app/views/layouts/_header.html.haml
- if current_admin_user
  = link_to "Back to Admin", admin_root_path
= yield :header

app/views/layouts/_recent_edits.html.haml
%div.recent-edit
  - if edit.created_at == edit.updated_at
    %p
      %strong= edit.try(:admin_user).try(:email)
      created
      %strong= link_to edit.integration.try(:title), edit_admin_integration_path(edit.integration_id)
      on
      %strong= edit.created_at.to_formatted_s(:short)
  - else
    %p
      %strong= edit.try(:admin_user).try(:email)
      updated
      %strong= link_to edit.integration.try(:title), edit_admin_integration_path(edit.integration_id)
      on
      %strong= edit.updated_at.to_formatted_s(:short)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmsSetup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/public.html.haml
!!! 5
%html
  %head
    %title
      LevelUp Setup
      = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
      = javascript_include_tag "application", "data-turbolinks-track" => true
      = csrf_meta_tags

  %body
    = render 'layouts/header'
    = yield